pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'ejemplo-nodejs'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
        DOCKER_NETWORK = 'jenkins_jenkins-netword'
    }

    stages {

        stage('Check branch') {
            steps {
                script {
                    def allowed = ['master', 'develop']
                }                
            }
        }


        stage('Checkout') {
            steps {
                echo 'Obteniendo codigo fuente'
                checkout scm  
            }
        }
 
        stage('Install Dependencies') {
            steps {
                echo 'Instalando dependencias'
                sh 'npm install'
            }
        }

        stage('Lint') {
            steps {
                echo 'Ejecutando  Linter'
                sh 'npm run lint || true'
            }
        }

        stage('Tests') {
            steps {
                echo 'Ejecutando pruebas'
                sh 'npm test'
            }
            post {
                always {
                    junit (testResults:'coverage/junit.xml', allowEmptyResults: true)
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Construyendo imagen de Docker'
                sh """
                    docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
                    docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
                """
            }
        }

        stage('Deploy') {
            steps {
                echo 'Despegando aplicacion'
                sh """
                    docker stop ${DOCKER_IMAGE} || true
                    docker rm ${DOCKER_IMAGE} || true

                    docker run -d \
                        --name ${DOCKER_IMAGE} \
                        --network ${DOCKER_NETWORK} \
                        -p 3000:3000 \
                        ${DOCKER_IMAGE}:latest
                """
            }
        }

        stage('Health Check') {
            steps {
                echo 'Verificando salud de la aplicacion'
                sh  """
                    sleep 5
                    curl -f http://${DOCKER_IMAGE}:3000/health || exit 1
                """
            }
        }
        
    }

    post {
        always {
            echo 'Limpiando workspace'
            cleanWs()
        }
        success {
            echo 'Pipeline completado exitosamente.'
        }
        failure {
            echo 'Pipeline fallo'
        }
    }
}